# Jekyll configuration for GitHub Pages
name: Terra Rent Car
description: Премиальная аренда автомобилей в Молдове

# GitHub Pages settings
baseurl: ""
url: "https://terrarentcar.md"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - node_modules
  - src
  - package.json
  - package-lock.json
  - vite.config.ts
  - tailwind.config.ts
  - tsconfig*.json
  - eslint.config.js
  - postcss.config.js
  - components.json
  - .env*
  - .gitignore
  - README.md
  - functions
  - netlify.toml

# Include only dist files
include:
  - dist

# Set the source directory to root
source: .
destination: .

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Terra Rent Car"

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Sitemap
sitemap:
  exclude:
    - /404.html
    - /robots.txt
    - /sw.js
    - /_headers
    - /_redirects
    - /CNAME
