[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_AIRTABLE_BASE_ID = "app2d5VGYA0UjVj9u"
  VITE_AIRTABLE_TOKEN = "patMiGkMfV2eHj8Bz.93dd90b012b1ce19e00368c03986794b45064f1d7d16bd91a99f38c4889aee8c"
  VITE_FIREBASE_API_KEY = "AIzaSyB41DRUbKWJHPxaFjMAwdrzWzbVKartNGg"
  VITE_FIREBASE_AUTH_DOMAIN = "terrarentcar-f1fda.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "terrarentcar-f1fda"
  VITE_FIREBASE_STORAGE_BUCKET = "terrarentcar-f1fda.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "114261195759"
  VITE_FIREBASE_APP_ID = "1:114261195759:web:8b8b8b8b8b8b8b8b8b8b8b8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google.com https://maps.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; frame-src 'self' https://www.google.com https://maps.googleapis.com; connect-src 'self' https://maps.googleapis.com;" 